#!/usr/bin/expect

set username [lindex $argv 0]
set IP       [lindex $argv 1]
set keyName  [lindex $argv 2]
set homedir  [lindex $argv 3]
set passwd   [lindex $argv 4]
set timeout  3

spawn ssh-copy-id -i "$homedir/.ssh/id_rsa$keyName" "$username@$IP"

expect {
	"*nter passphrase*" { exit 2 }
	eof { exit 2 }
	timeout { exit 2 }
	"*(yes/no)?*" { send "yes\n";exp_continue }
	"password" { send "${passwd}\n" }
	"*]*" { exit 0 }
}
expect eof
