#!/usr/bin/expect 
set timeout 10
# 参数是从0开始的
set PORT [lindex $argv 0] 
set SRCFILE [lindex $argv 1] 
set USERNAME [lindex $argv 2]  
set IP [lindex $argv 3]  
set TARPATH [lindex $argv 4]  
set PASSWORD [lindex $argv 5]

spawn scp -P ${PORT}  ${SRCFILE} ${USERNAME}@${IP}:${TARPATH}
# 输入脚本模板,expect { 必须在同一行
expect {
  "(yes/no)?"
  {
    send "yes\r"
    expect "*assword:" { send "$PASSWORD\r"}
  }
  "*assword:"
  {
    send "$PASSWORD\r"
  }
}
expect "100%"
interact
